### ISSUE TITLE
Make sense of key and rows

### ISSUE THREAD

**Issue by efurban** [corelevel/DatabaseArchiving#2]
It's been working great! 
However I couldn't make much sense of the values for keyMaxValue, LastArchivedKey and LastArchivedKey ( DataCopyBatchSize = 100, keyCopyBatchSize = 100 ). 
Also the RowsCopied is always 0 though the data were copied to the destination.  Just wondering if you could share some details before I dig into the code.  Thanks. 

![image](https://user-images.githubusercontent.com/3455707/180871661-fcb75bcc-7eb5-4fa3-8984-8635db7b478d.png)

**Comment by corelevel** [comment]
Not sure why RowsCopied is always 0. Do you have any errors?

LastArchivedKey - used to resume archiving in case something(error) happens in the middle of the process. After restart, the script will not copy all data again.
Same for logic for LastPurgedKey.
KeyMaxValue - is just a max value of surrogate primary key in _source working table_. It's used to check do we have any rows to archive/purge or not.

**Comment by efurban** [comment]
Got it working! I had to set $bulkCopy.NotifyAfter = 1, since the number of rows copied is less than BatchSize / 10. 
So for KeyMaxValue:  is this the max PK in the source working table for each archiving process / run?  looks like it's the number of rows should be copied?

**Comment by corelevel** [comment]
I'll take a look. That may be an error in my script

**Comment by efurban** [comment]
I do see some other issues, where nothing was copied but data was purged, when AlwaysRunCheck = True. 
Let me know. thank you

**Comment by efurban** [comment]
after fixing some configuration issues, it all seems to be working now.  Will keep testing more. thank you!
